### ISSUE TITLE
Create Project Table

### ISSUE THREAD

**Issue by alm0st907** [alm0st907/codecon-422#25]
This table should contain things such as 
- project name
- task list
- defcon scale
- launch date

more fields may need to be added but ideally the 3 tables sync to fill in any gaps as necessary.

**Comment by bergerMichael** [comment]
For now I will not be including a task list column because sql does not support lists. Instead, we should consider using the projectName field as a primary key for the Project table and the projectName column of the Task table as a foreign key that references the Project table. This way we can use stronger queries to access project data.

**Comment by alm0st907** [comment]
@bergerMichael In hindsight, there is no need for a task list. You are correct. The task table itself should just have the ID or a name field like you are saying to associate between the two, and the API can assemble it into a list or list like format for display.
